### ISSUE TITLE
Order details not showing on AffiliateWP 1.8.1

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-order-details-for-affiliates#14]
A bug was introduced via https://github.com/AffiliateWP/AffiliateWP/commit/0663298af907e40115d94a2ce6481ee483002019. When a user attempts to navigate to the Order Details tab, the URLs tab is shown, even though the query string is present in the omnibar: `http://wc.local.dev/affiliate-area/?tab=order-details`.

We need to add the new function that introduced to Order Details:
https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/blob/master/affiliatewp-order-details-for-affiliates.php#L199
https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/blob/master/affiliatewp-order-details-for-affiliates.php#L223
![screen shot 2016-05-19 at 3 25 46 pm](https://cloud.githubusercontent.com/assets/4752949/15408472/ff3a18be-1dd5-11e6-90e5-b863cffd5a58.png)

**Comment by pippinsplugins** [comment]
We can fix this by registering the `Order Details` tab or by adjusting core to not require the tab to be registered.

**Comment by DrewAPicture** [comment]
Added a PR: #15

**Comment by sumobi** [comment]
@DrewAPicture @pippinsplugins Tested and all is good. I can push out an update soon.

**Comment by sumobi** [comment]
Update has been deployed
