### ISSUE TITLE
Allow paid referrals to be shown in order details tab

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-order-details-for-affiliates#16]
Based on survey feedback:

> The order dashboard is not working well. When I click on status PAID, my affiliates loose all the order details!!! They loose trust in me because of this, as it looks like I am hiding information on purpose, so this is a big issue to be solved ASAP.

When a referral is "paid" it's disappearing from the order details tab since the template file is only set to show "unpaid" referrals. 

We can either add "paid" into the arguments, or add an admin option that lets you choose which statuses should be shown.

**Comment by pippinsplugins** [comment]
I'd vote for defaulting to paid and unpaid

**Comment by sumobi** [comment]
Yeah, having another support ticket today about this very issue sealed the deal.

**Comment by roydelaat** [comment]
Dear @sumobi 

I am looking for a solution for the exact same problem. Did you already find a solution? If so, could you give me the solution?

**Comment by sumobi** [comment]
@roydelaat 

We will most likely update the template file to show unpaid and paid as per https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/issues/16#issuecomment-238552734 however you can do this right now by 

1. Copying the template file to your child theme and editing it. Change the highlighted line to:

`'status'       => array( 'unpaid', 'paid')`

https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/blob/master/templates/dashboard-tab-order-details.php#L10

or

2. Use the `affwp_odfa_referral_args filter`: https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/blob/master/templates/dashboard-tab-order-details.php#L6

**Comment by roydelaat** [comment]
Thanks, this works!

**Comment by amdrew** [comment]
You're welcome!

**Comment by pippinsplugins** [comment]
@amdrew ready.
