### ISSUE TITLE
Show coupon discount codes used on order details

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-order-details-for-affiliates#23]
It would be helpful to show coupons used in the order details, especially if the coupon belongs to an affiliate.  This would help them track their referrals since a visit is not recorded if only the coupon is used to generate a referral.

**Comment by pippinsplugins** [comment]
@gspice PR submitted, could you give it a test please?

**Comment by gspice** [comment]
@pippinsplugins Looks good!
