### ISSUE TITLE
Paid and pending order details 

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-order-details-for-affiliates#27]
As an affiliate you can only see the order details for the unpaid referrals. It might be nice if there was a way to see all order details for paid and pending orders as well.

**Comment by sumobi** [comment]
This is possible already using the `affwp_odfa_referral_args` filter: https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/blob/master/templates/dashboard-tab-order-details.php#L6

Perhaps we could add a multi-check admin option to make it easier.

**Comment by sumobi** [comment]
Dupe: https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/issues/16

As per https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/issues/16#issuecomment-308080232 we should just change it to unpaid and paid. I don't think pending orders should be seen by an affiliate by default.
