### ISSUE TITLE
Request to add last name to the Name: entry, currently showing first_name

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-order-details-for-affiliates#28]
User requests to add the last name for the **Name:** entry, currently it only shows first name from the user account data.  If you have a shipping or billing address, that shows the full name however in this case they did not.

https://secure.helpscout.net/conversation/407569768/64201/?folderId=205529

https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/blob/master/includes/class-order-details.php#L177

**Comment by pippinsplugins** [comment]
Ready for testing!

**Comment by gspice** [comment]
Looks good in my test.
