### ISSUE TITLE
Add order # 

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-order-details-for-affiliates#29]
Add order number (from the reference column on the Referral) to the Order Details output.

**Comment by pippinsplugins** [comment]
This is already shown:
<img width="885" alt="screen shot 2017-08-10 at 3 59 53 pm" src="https://user-images.githubusercontent.com/1034109/29191920-fde53db6-7de4-11e7-8054-88ca30ed0459.png">
