### ISSUE TITLE
Shortcode not filterable, needs to support multiple statuses

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-order-details-for-affiliates#36]
How it is currently, the `affwp_odfa_referral_args` filter has no effect on the `[affiliate_order_details]` shortcode. In addition, the shortcode isn't affected if the args are modified from the actual template file, which the shortcode uses. This doesn't make much sense.

For example, placing `[affiliate_order_details]` on a page should show the default number of referrals, `100`. This works.

Placing `[affiliate_order_details number="50"]` should show 50 referrals. This works.

However, if we then filtered the number of referrals using the `affwp_odfa_referral_args` filter to show `5` referrals, the first example would still show `100`, not `5` as expected. 

There's also no need to specify defaults in 2 places:

https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/blob/master/includes/class-shortcodes.php#L48-L50

and 

https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/blob/master/templates/dashboard-tab-order-details.php#L9-L11

And finally, the shortcode needs to support passing multiple statuses, `unpaid` and `paid`. This is so if the default shortcode is filtered to show 1 status, the shortcode can still be used with both statuses, and override the filter. These can be passed in as comma separated values.

**Comment by amdrew** [comment]
Will finish this off and then push out 1.1.4

**Comment by amdrew** [comment]
WIP https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/pull/37

Going to give it a bit more testing. Template file is a lot cleaner now.

**Comment by amdrew** [comment]
Closing, can't fault it.

**Comment by gspice** [comment]
@amdrew  I'm seeing order details for status values of Unpaid only in the Affiliate Area.  Is this correct behavior by default?

**Comment by gspice** [comment]
Question above was answered - was a quirk in the free add-ons download page.
