### ISSUE TITLE
Support WooCommerce Sequential Order Numbers

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/affiliatewp-order-details-for-affiliates#4]
A Customer has requested integration with the WooCommerce Sequential Order Numbers extension. When  these custom order numbers are shown, the Order Details add-on still shows the default WC order numbers.

ref: https://secure.helpscout.net/conversation/108451380/13749/

**Comment by sumobi** [comment]
Closed via https://github.com/affiliatewp/affiliatewp-order-details-for-affiliates/commit/97b6806c6cd6411983436584eacff94b7aeebcd6

**Comment by gspice** [comment]
This appears to have been re-broken.  

I'm using:
* Order Details for Affiliates version `1.1.5`
* WooCommerce Sequential Order Numbers version `.1.9.0`
* WooCommerce `3.7.0`

The sequential order number shows correctly in Affiliates > Referrals and the `Reference` column links to the correct Woo order, however, the **Order Details** tab shows the native Woo order number.
