### ISSUE TITLE
Not supporting WooCommerce Sequential Order Numbers

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-order-details-for-affiliates#57]
This appears to have been re-broken from #4 

### My current testing setup:
* Order Details for Affiliates version `1.1.5`
* WooCommerce Sequential Order Numbers version `1.9.0`
* WooCommerce `3.7.0`

The sequential order number shows correctly in _Affiliates > Referrals_ and the `Reference` column links to the correct WooCommerce order, however, the **Order Details** tab shows the native Woo order number and not the sequential order number.   

Reported on this ticket where he's using the pro version, I'm testing with the free version:
https://secure.helpscout.net/conversation/948475093/130674/

**Comment by gspice** [comment]
Another customer reporting this:
https://secure.helpscout.net/conversation/1389227909/174508?folderId=1170842

>can the order number in order details be the order number in my inside system
i am using WooCommerce Sequential Order Numbers to be order number Sequential but in AffiliateWP order details the order number is different ​​

**Comment by DrewAPicture** [comment]
Added to the Issue Blitz project and milestoned for 1.1.6.

**Comment by dbeja** [comment]
PR: #70

**Comment by dbeja** [comment]
@gspice 

Merged #70 against `release/1.1.6`.
