### ISSUE TITLE
Order Details is not translated in zh_TW

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-order-details-for-affiliates#59]
### Expected behavior
When I change the site language to **zh_TW**, the text within the Order Details tab will be translated. 

### Actual behavior
When I change the site language to **zh_TW**, the text within the Order Details tab is _not_ be translated. 

A [customer](https://secure.helpscout.net/conversation/1022784220/0/?folderId=205529) ran into this and I was able to replicate it: 
![image](https://user-images.githubusercontent.com/4752949/70178077-dd9e2800-16db-11ea-80a8-e6a3c5531582.png) 
![image](https://user-images.githubusercontent.com/4752949/70179186-e55ecc00-16dd-11ea-9857-1cc30ef38e91.png) 

### Steps to reproduce the behavior 
1) Change site language do **zh_TW**
2) Navigate to the affiiate area and the text within the Order Details tab will not be translated. 

### Information:
PHP Version: 7.0.33
AffiliateWP Version: 2.4.2
Order Details For Affiliates Version: 1.1.5
WordPress Version: 5.3

Any other relevant information:

We added **zh_TW** in https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/issues/35, and it looks like it needs to be refreshed as there are now fuzzy strings, but we could also transition all translation files over to .org as proposed in https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/issues/50.

**Comment by DrewAPicture** [comment]
As we've seen before in many previous reports, the likely cause of this is that the translated string is marked "fuzzy" or "needs work". So that should be the first thing we look for in these situations.

**Comment by amdrew** [comment]
Drew's correct, it will not show correctly if the string is marked as fuzzy:

Here's my local site, before and after correcting the translation:

<img width="653" alt="Screen Shot 2019-12-05 at 11 55 08 AM" src="https://user-images.githubusercontent.com/52581/70188683-3c07ec80-1756-11ea-893c-ac93e14de6ae.png">

After (fixed):

<img width="650" alt="Screen Shot 2019-12-05 at 11 55 27 AM" src="https://user-images.githubusercontent.com/52581/70188684-3c07ec80-1756-11ea-8a07-96cad4872005.png">

**Comment by amdrew** [comment]
Note: I've imported the current zh_TW translations from this add-on to .org but there's still work needed with fuzzy strings etc. Translations are currently waiting approval. We really need to direct any customer interested in translations to the repo so they can help us tidy them up. 

Here's the current state of zh_TW in the stable release: https://translate.wordpress.org/projects/wp-plugins/affiliatewp-order-details-for-affiliates/stable/zh-tw/default/

And we still need to look at #50 to make sure it's all working.

**Comment by michaelbeil** [comment]
I will direct the customer to .org to do any work on fuzzy strings and to add to the zh_TW translation.

**Comment by amdrew** [comment]
Thanks @michaelbeil!

**Comment by michaelbeil** [comment]
I'm going to close out this issue then.
