### ISSUE TITLE
Referrals with no context breaking output of page

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-order-details-for-affiliates#60]
A customer's order details tab stopped showing the rest of the page after a specific referral. Most likely a fatal error of some kind.

Conversation: https://secure.helpscout.net/conversation/1026374428/139459/

I discovered there was a referral not showing on the page (the next referral _after_ the one that _was_ showing) which did not have a `context` set. This was likely manually added by the customer. 

Adding a context to this referral (and another one further down the list) fixed the page and it then loaded correctly.

I haven't replicated the issue locally but I'm almost certain it's because the add-on relies heavily on a context being set for each referral. Since the referral did not have one, it caused a fatal error and broke the page.

**Comment by DrewAPicture** [comment]
PR: #61 

The PR sets up `default` clauses for switch statements in `ODFA::exists()` and `ODFA::get()`. The way the `exists()` method is written, it defaults to `true` and if `context` isn't set or isn't EDD or WC, the switch statements gets skipped entirely and then method always returns `true`. The new default clause defaults to `false`.
