### ISSUE TITLE
Improve inline documentation throughout

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/affiliatewp-order-details-for-affiliates#63]
There's a lot of missing and/or incomplete inline documentation that we could add to improve the developer experience considerably. Some improvements were already made in the PR for #60.

**Comment by DrewAPicture** [comment]
@dbeja Would you like to give improving the inline docs for this add-on a shot? We by no means need to be 100% complete but there's always room for improvement!

**Comment by dbeja** [comment]
Yes, @DrewAPicture, I'll definitely work on this one.

**Comment by dbeja** [comment]
PR: #71

**Comment by DrewAPicture** [comment]
Merged #71 against `release/1.1.6`
