### ISSUE TITLE
Adjust how used coupon codes are retrieved in WooCommerce 3.7+

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-order-details-for-affiliates#64]
Just as we did in https://github.com/AffiliateWP/AffiliateWP/issues/3087, we also need to update our WooCommerce integration in Order Details For Affiliates as a [customer reported](https://secure.helpscout.net/conversation/1193168647/157171?folderId=205527):
>You have usage of function get_used_coupons() for Woocomerce which is deprecated.

>Use WC_Abstract_Order::get_coupon_codes instead.
>Deprecated in version 3.7.

>Could you please check. 
<img width="442" alt="Capture" src="https://user-images.githubusercontent.com/4752949/84544893-85855580-acfe-11ea-97d5-21d2a9e19534.PNG">

The screenshot is referencing the following line: 
https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/blob/7d0d8c979b761fdb73fabe0bbfb3f5db696f3344/includes/class-order-details.php#L309

**Comment by DrewAPicture** [comment]
@alexstandiford I guess we'll need to drop in a check against WooCommerce 3.7 to switch up the method used. Mind tackling a PR for this?

**Comment by tubiz** [comment]
PR: #67

**Comment by DrewAPicture** [comment]
Whoops!

**Comment by DrewAPicture** [comment]
Merged #67 against `release/1.1.6`
