### ISSUE TITLE
Visits Tracking

### ISSUE THREAD

**Issue by flowdee** [affiliatewp/affiliatewp-order-details-for-affiliates#8]
As far as I can see views are not being tracked for external referral links?!

This is absolutely mandatory in my opinion. My affiiliates want to see which ref links work well and which not but without the visits statistics it's impossible to be transparent.

**Comment by sumobi** [comment]
Hi @flowdee, can you elaborate a bit more? how does this integrate with the order details for affiliates add-on?

**Comment by flowdee** [comment]
Damn sorry wrong repo :dash:
